name: flutter_image
version: 3.0.0
description: >
  Image utilities for Flutter: providers, effects, etc
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/flutter_image

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  quiver: ^3.0.1
  test: any

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"
